language: python

branches:
  only:
    - master

matrix:
  include:
    - python: '3.6'
    - python: '3.7'
      dist: xenial
      sudo: true

cache: pip

script:
  - pytest
  - mypy pypokedex
  - flake8
